# Generated by Django 3.2.25 on 2025-12-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255)),
                ('title_ar', models.CharField(max_length=255)),
                ('summary_en', models.TextField()),
                ('summary_ar', models.TextField()),
                ('content_en', models.TextField(blank=True)),
                ('content_ar', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('external_link', models.URLField(blank=True, help_text='Link to external article')),
                ('published_date', models.DateField()),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Update',
                'verbose_name_plural': 'News Updates',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home Page'), ('about', 'About Page'), ('founder', 'Founder Page'), ('center', 'Human Rights Center'), ('forum', 'Dialogue Forum'), ('publications', 'Publications'), ('contact', 'Contact Page')], max_length=50, unique=True)),
                ('hero_title_en', models.CharField(blank=True, max_length=255)),
                ('hero_title_ar', models.CharField(blank=True, max_length=255)),
                ('hero_subtitle_en', models.TextField(blank=True)),
                ('hero_subtitle_ar', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='pages/heroes/')),
                ('content_en', models.TextField(blank=True, help_text='Main page content in English')),
                ('content_ar', models.TextField(blank=True, help_text='Main page content in Arabic')),
                ('meta_title_en', models.CharField(blank=True, max_length=70)),
                ('meta_title_ar', models.CharField(blank=True, max_length=70)),
                ('meta_description_en', models.CharField(blank=True, max_length=160)),
                ('meta_description_ar', models.CharField(blank=True, max_length=160)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Content',
                'verbose_name_plural': 'Page Contents',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='info@riadseiflb.org', max_length=254)),
                ('phone', models.CharField(default='+961 1 234 567', max_length=20)),
                ('address_en', models.CharField(default='Damascus, Syria', max_length=255)),
                ('address_ar', models.CharField(default='دمشق، سوريا', max_length=255)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('footer_text_en', models.TextField(default='Dedicated to the memory and values of the Damascus Spring, working towards a free and democratic Syria for all its citizens.')),
                ('footer_text_ar', models.TextField(default='مكرسة لذكرى وقيم ربيع دمشق، وتعمل نحو سوريا حرة وديمقراطية لجميع مواطنيها.')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('role_en', models.CharField(max_length=100)),
                ('role_ar', models.CharField(max_length=100)),
                ('bio_en', models.TextField(blank=True)),
                ('bio_ar', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name_en'],
            },
        ),
    ]
