# Generated by Django 5.2.11 on 2026-04-16 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_seed_latest_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Job Opportunity', 'verbose_name_plural': 'Job Opportunities'},
        ),
        migrations.AlterModelOptions(
            name='newsupdate',
            options={'ordering': ['-published_date', '-created_at', '-id'], 'verbose_name': 'News Update', 'verbose_name_plural': 'News Updates'},
        ),
    ]
