# Generated by Django 3.2.25 on 2025-12-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_ar', models.CharField(max_length=255, verbose_name='Title (Arabic)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('description_ar', models.TextField(verbose_name='Description (Arabic)')),
                ('category', models.CharField(choices=[('report', 'Report / تقرير'), ('policy_brief', 'Policy Brief / ورقة سياسات'), ('manual', 'Manual / دليل'), ('research', 'Research / بحث'), ('article', 'Article / مقال')], max_length=50)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='publications/pdfs/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='publications/covers/')),
                ('published_date', models.DateField(verbose_name='Publication Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
