# Generated by Django 5.2.12 on 2026-04-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.CharField(choices=[('report', 'Report'), ('policy_brief', 'Policy Brief'), ('manual', 'Manual'), ('research', 'Research'), ('article', 'Article'), ('archive', 'Archive')], max_length=50),
        ),
    ]
