# Generated by Django 3.2.25 on 2025-12-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_ar', models.CharField(max_length=255, verbose_name='Title (Arabic)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('description_ar', models.TextField(verbose_name='Description (Arabic)')),
                ('event_type', models.CharField(choices=[('dialogue', 'Dialogue Session / جلسة حوار'), ('workshop', 'Workshop / ورشة عمل'), ('conference', 'Conference / مؤتمر'), ('webinar', 'Webinar / ندوة عبر الإنترنت'), ('training', 'Training / تدريب')], default='dialogue', max_length=50)),
                ('date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, help_text='For multi-day events', null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_online', models.BooleanField(default=False)),
                ('online_link', models.URLField(blank=True, help_text='Zoom/Teams link for online events')),
                ('registration_url', models.URLField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/covers/')),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-date'],
            },
        ),
    ]
