# Generated by Codex on 2026-03-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemoryPhoto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title_en", models.CharField(max_length=255)),
                ("title_ar", models.CharField(max_length=255)),
                ("description_en", models.TextField(blank=True)),
                ("description_ar", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="forum/memory/")),
                ("date", models.CharField(blank=True, max_length=50)),
                ("is_published", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Memory Photo",
                "verbose_name_plural": "Memory Photos",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ArchiveItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title_en", models.CharField(max_length=255)),
                ("title_ar", models.CharField(max_length=255)),
                ("description_en", models.TextField(blank=True)),
                ("description_ar", models.TextField(blank=True)),
                ("date", models.CharField(blank=True, max_length=50)),
                ("is_published", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("external_link", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "Archive Item",
                "verbose_name_plural": "Archive Items",
                "ordering": ["order", "id"],
            },
        ),
    ]
